#!/usr/bin/env php
<?php

$kahlan = 'https://raw.githubusercontent.com/crysalead/kahlan/master/composer.json';
$jitVersion = json_decode(file_get_contents($kahlan), true)['require']['crysalead/jit'];

`COMPOSER_ROOT_VERSION={$jitVersion} composer install`;
